### ISSUE TITLE
Upgrade RxJava

### ISSUE THREAD

**Issue by aaloise** [grails-plugins/grails-rxjava#1]
Any chance to upgrade or create a separate branch to RxJava 2?

**Comment by graemerocher** [comment]
Master branch is now RxJava 2.0... however since most libraries (MongoDB RX etc. still use RxJava 1.x) it will be a while before it is useful. See https://github.com/grails-plugins/grails-rxjava/commit/f7997e3f9004144c8134ab955be704567bd7d4b5
